### ISSUE TITLE
What version of MATLAB should I use to run the demo?

### ISSUE THREAD

**Issue by ChenGQ26** [ankhoreva/LucidDataDreaming#1]
I tried to run the demo in MATLAB R2014a/ R2016b/ R2017b.  But all of them failed.

**Comment by g4nym3de** [comment]
Any luck?

**Comment by ZhaoJinHA** [comment]
Hi, I run demo.m successfully in matlab 2017b in Ubuntu system. The only modification is that I comment the first line:
"cd lucid_data_dreaming"

**Comment by yelantingfeng** [comment]
Well, you may need to recompile the CSH codes. BTW, I find this matlab version quite slow and I cannot figure out what the problem is. I reimplement its logic with python and opencv, you can take a try.

**Comment by ChenGQ26** [comment]
@yelantingfeng Thanks! I had solved it in the same way.
